# This configuration spins up a client with dummy sensors and publishes via MQTT
# Ideal for testing on a laptop :)

EventSinks:
    - MQTTEventSink:
        class: "mqtt_event_sink.MQTTEventSink"
        hostname: "iqueue.ics.uci.edu"
        #hostname: "dime.smartamerica.io"
        #hostname: "m2m.eclipse.org"
        hostport: 1883
        username: null
        password: null
        keepalive: 60

Applications:
    - Thread:
        class: "dummy_threaded_application.DummyThreadedApplication"
    - LocationManager:
        class: "location_manager.LocationManager"

Sensors:
    - InternetAccessSensor:
        class: "internet_access_virtual_sensor.InternetAccessVirtualSensor"
        dev_name: "net0"
    - HBSensor:
        class: "heartbeat_virtual_sensor.HeartbeatVirtualSensor"
        dev_name: "hb0"
        interval: 60
    - DummySeismicSensor:
        class: "dummy_sensors.dummy_csn_virtual_sensor.DummyCSNVirtualSensor"
        dev_name: "accel0"
    - GeoIPSensor:
        class: "location_sensors.geo_ip_virtual_sensor.GeoIPVirtualSensor"
        dev_name: "geoip0"
# VirtualSensors that detect higher-level events: should work with dummy_sensors
    - PIRNoMotionSensor:
        class: "pir_no_motion_virtual_sensor.PIRNoMotionVirtualSensor"
        dev_name: "nomot0"
    - LightFlashSensor:
        class: "light_flash_virtual_sensor.LightFlashVirtualSensor"
        dev_name: "flash0"
# Dummy presence_sensors
    - DummyPIRSensor:
        class: "dummy_sensors.dummy_pir_virtual_sensor.DummyPIRVirtualSensor"
        dev_name: "pir0"
# Dummy environmental_sensors
    - TempHighSensor:
        class: "temperature_high_virtual_sensor.TemperatureHighVirtualSensor"
        dev_name: "heat0"
    - DummyLightSensor:
        class: "dummy_sensors.dummy_light_virtual_sensor.DummyLightVirtualSensor"
        dev_name: "light0"
    - DummyGasSensor:
        class: "dummy_sensors.dummy_gas_virtual_sensor.DummyGasVirtualSensor"
        dev_name: "gas0"
    - DummyTempSensor:
        class: "dummy_sensors.dummy_temperature_virtual_sensor.DummyTemperatureVirtualSensor"
        dev_name: "cel0"
